// Dry goods & equipment — recovered from the legacy Shopify catalog
// (these products still live in the Shopify backend; website id == Shopify
// handle so cart checkout resolves the variant with no extra mapping).
import type { Product } from "./mockData";

export const dryGoodsProducts: Product[] = [
  {
    id: "ai-hydra-64-hd-led-reef-light-black",
    name: "AI \u2013 Hydra 64 HD LED Reef Light \u2013 Black",
    description: "More Color, More Spread, More Power, and More Refined A new generation of Aqua Illumination Hydra lighting is here! The Hydra 64 HD has been redesigned making the reef lights more efficient with better aesthetics. The Hydra Lights have been a staple in the reefing community for years and the new Hydra 64 HD Lights take the same great features and benefits while using more efficient hardware that ultimately gives better light and spread throughout your aquarium.",
    category: "Dry Goods",
    subCategory: "Lighting",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 785.99,
    wholesalePrice: 589.49,
    imageGradient: "from-indigo-800 to-sky-900",
    tags: ["lighting", "equipment", "dry goods"],
  },
  {
    id: "aquael-air-pump-miniboost-100",
    name: "Aquael Air Pump MiniBoost 100",
    description: "The Aquael Air Pump MiniBoost 100 is a high-quality and efficient mini air pump that provides reliable and quiet performance for your aquarium. With a compact and durable design, this air pump is perfect for use in small and medium-sized aquariums. The MiniBoost 100 features a powerful motor that produces a high airflow rate, ensuring that your aquarium water is properly oxygenated for your fish and other aquatic life. It also has an adjustable air flow rate, allowing you to easily control the amount of air being released. With its low noise level, the MiniBoost 100 won't disturb your aquarium inhabitants or your peace and quiet.",
    category: "Dry Goods",
    subCategory: "Pumps & Flow",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 25.99,
    wholesalePrice: 19.49,
    imageGradient: "from-slate-700 to-blue-900",
    tags: ["air pump"],
  },
  {
    id: "aquael-multikani-expandable-canister-filter",
    name: "Aquael Multikani expandable canister filter",
    description: "The Aquael Multikani Expandable Canister Filter is a powerful and efficient filtration system that provides superior water quality for your aquarium. With its modular design and expandable capacity, this filter can be customized to meet the specific needs of your aquarium and its inhabitants. The Multikani canister filter features a multi-stage filtration system that includes mechanical, biological, and chemical filtration. Its advanced filtration media ensures excellent water clarity and a healthy environment for your fish and other aquatic life. The canister filter's expandable capacity allows for easy customization, making it ideal for use in a wide range of aquarium sizes and setups.",
    category: "Dry Goods",
    subCategory: "Filtration",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 86.99,
    wholesalePrice: 65.24,
    imageGradient: "from-slate-700 to-cyan-900",
    tags: ["freshwater", "saltwater"],
  },
  {
    id: "aquael-pat-mini-tiny-turbine-filter-for-5-30-gallon-tank",
    name: "Aquael PAT Mini Tiny Turbine Filter (for 5-30 gallon tank)",
    description: "Product Description: Qty: 1 AQUAEL PAT MINI is a tiny turbine filter intended for use in small freshwater aquariums. This device consists of a small head and a carefully selected filter sponge. Thanks to the innovative design, the maximum throughput of the filter head reaches 400 l/h, which is comparable to the typical performance of a medium-sized turbine aquarium filter. Despite its high performance, the filter operates at a power consumption of 4W or less. Given its specifications, PAT MINI can provide efficient filtration even in a 120-liter tank.",
    category: "Dry Goods",
    subCategory: "Filtration",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 45.99,
    wholesalePrice: 34.49,
    imageGradient: "from-slate-700 to-cyan-900",
    tags: ["freshwater", "saltwater"],
  },
  {
    id: "aquaforest-di-resin-1l-for-rodi",
    name: "Aquaforest DI Resin 1L for RODI",
    description: "The Aquaforest DI Resin 1L for RODI (Reverse Osmosis Deionization) is a premium-quality resin designed for use with your RODI system to purify water for your aquarium. This resin removes impurities such as minerals, metals, and other contaminants that can be harmful to your aquarium inhabitants. The Aquaforest DI Resin is made from high-quality materials and undergoes a rigorous purification process to ensure consistent performance and reliability. It is easy to use and can be easily replaced when depleted. With its large 1L capacity, the Aquaforest DI Resin provides long-lasting and effective purification for your aquarium water.",
    category: "Dry Goods",
    subCategory: "Water Treatment",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 69.99,
    wholesalePrice: 52.49,
    imageGradient: "from-teal-800 to-slate-900",
    tags: ["water treatment", "equipment", "dry goods"],
  },
  {
    id: "aquarium-decorations-non-toxic-pirate-themed-for-freshwater-or-saltwater",
    name: "Aquarium Decorations Non-Toxic Pirate Themed for Freshwater or Saltwater",
    description: "Product Description: Qty: 1 piece Looking for a way to spruce up your tank? Check out all the different pirate-themed designs available. Pick one or a variety! Options to chose from: Resin Ornament \u2013 3.1\u2033 Treasure Chest With Pearls-Dimensions: 3.35 x 2.36 x 3.15 Resin Ornament \u2013 4.1\u2033 Mossy Skull-Dimensions: 4.13 x 6.10 x 4.13 Resin Ornament \u2013 4.3\u2033 Coral Habitat-Dimensions: 4.84 x 4.53 x 4.33 Resin Ornament \u2013 4.9\u2033 Treasure Swim-Through-Dimensions: 5.51 x 5.91 x 4.88 Resin Ornament \u2013 8.9\" Galleon Shipwreck Resin Ornament \u2013 Pirate Skull w/ Treasure-Dimensions: 2.56 x 2.95 x 2.68 Available options: Treasure Swim-Through, Mossy Skull, Coral Habitat, Treasure Chest with Pearls, Galleon Shipwreck, Pirate Skull with Treasure. Listed price is for Treasure Swim-Through.",
    category: "Dry Goods",
    subCategory: "Decor",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 31.99,
    wholesalePrice: 23.99,
    imageGradient: "from-stone-700 to-amber-950",
    tags: ["decor", "equipment", "dry goods"],
  },
  {
    id: "aquastik-epoxy-putty-coraline-red-4-oz-stick-for-underwater-coral-adhesion",
    name: "AquaStik Epoxy Putty Coraline Red 4 oz stick for underwater coral adhesion",
    description: "The AquaStik Epoxy Putty Coraline Red 4 oz Stick is the ideal solution for underwater coral adhesion in your aquarium. This easy-to-use epoxy putty stick is designed to securely attach live coral fragments, rocks, and decorations to your aquarium floor or walls. The Coraline Red color of this AquaStik Epoxy Putty complements the colors of coralline algae, making it a natural-looking solution for your aquarium. It is also safe to use with fish and invertebrates and will not leach harmful substances into your tank. This epoxy putty stick is made from high-quality materials and is specially formulated to cure underwater, making it ideal for use in saltwater and freshwater aquariums.",
    category: "Dry Goods",
    subCategory: "Accessories",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 19.99,
    wholesalePrice: 14.99,
    imageGradient: "from-slate-600 to-slate-900",
    tags: ["accessories", "equipment", "dry goods"],
  },
  {
    id: "boyd-enterprises-chemipure-blue",
    name: "Boyd Enterprises-Chemipure Blue",
    description: "Boyd Enterprises-Chemipure Blue is a high-quality, chemical filtration media that keeps your aquarium water crystal clear and healthy. Designed specifically for marine and reef aquariums, Chemipure Blue removes impurities and odors from the water, ensuring a healthy and vibrant environment for your aquatic pets. Chemipure Blue contains a blend of high-grade activated carbon, ion exchange resins, and synthetic adsorbents that work together to remove dissolved organics, toxins, and other pollutants from your aquarium water. This unique blend helps to reduce the build-up of harmful substances that can cause algae growth, fish stress, and disease. Available options: 5 Nano Packets, 2 Pack of Chemi Pure 5.5 Oz, 2 Pack of Chemi Pure 11 Oz. Listed price is for 5 Nano Packets.",
    category: "Dry Goods",
    subCategory: "Water Treatment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 15.0,
    wholesalePrice: 11.25,
    imageGradient: "from-teal-800 to-slate-900",
    tags: ["chemi pure"],
  },
  {
    id: "c02-begginer-bundle-package-ista-c02-cans-diffuser-set-co2-indicator-solution",
    name: "C02 Begginer Bundle Package: ISTA C02 Cans & Diffuser Set",
    description: "Gulfstream tropical ista co2 diffuser set. Undisputable quality and reliability. These are the most practical diffusers available. The Ista Disposable CO2 Can 3 Pack replacement is for the ista Disposable CO2 Diffuser Set. Maximize the lifespan of your aquarium plants with the Gulfstream Tropical ISTA C02 Diffuser Set. Backed by undeniable quality and reliability, these diffusers are the most practical on the market. Plus, with easy-to-replace Ista Disposable CO2 Can 3 Packs, it's a convenient and cost-effective solution for maintaining the health of your aquatic ecosystem.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 59.99,
    wholesalePrice: 44.99,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["co2 equipment", "equipment", "dry goods"],
  },
  {
    id: "caribsea-liferock-belize-branch-marine-reef-aquarium-20lb-or-40lb",
    name: "CaribSea Liferock Belize Branch Marine Reef Aquarium 20lb or 40lb",
    description: "Product Description: Qty: (1) 20lb or 40 lb box Real aragonitic base rock, not cement, no curing. Extensive macro and micro-porosity infused with spored bacteria for outstanding biological performance. Clean and safe for all fish and inverts, environmentally responsible each piece being very unique. begins as a sunlit piece of Pleistocene era seafloor thriving with living creatures. Over the next 100 millennia and the retreat of the ocean, this ancient piece of seafloor, now well inland, has formed a pure, aragonite-bearing rock. This clean base rock is 97% calcium carbonate with minor and trace elements such as strontium, magnesium, and barium. Available options: 20 lbs, 40 lbs. Listed price is for 20 lbs.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Saltwater",
    availability: "OUT OF SEASON",
    price: 98.99,
    wholesalePrice: 74.24,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["aquascapes", "caribsea", "ecoscapes", "reef", "saltwater"],
  },
  {
    id: "caribsea-arag-alive-natural-reef-substrate",
    name: "CaribSea , ARAG-ALIVE! \u2013 Natural Reef Substrate",
    description: "Typical Size: 3.0 - 5.5mm Average Density: 85 pounds per cubic foot Item: 16 lb bag Product Description: Bring the world\u2019s most exotic reefs into your home with CaribSea\u2019s Arag-Alive!\u2122 substrates. Eight environmentally accurate ecoscapes, developed through CaribSea\u2019s cooperation with public aquariums and zoological parks where authenticity is a must, Arag-Alive!\u2122 makes any aquarium uniquely yours. Arag-Alive!\u2122 makes it easy to set up an aquarium. It\u2019s ready to work, clears quickly, and contains millions of live bacteria to cycle super fast and create a natural biological balance.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 37.99,
    wholesalePrice: 28.49,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "caribsea-bimini-pink-arag-alive-saltwater-reef-substrate-10-lb-or-20-lb",
    name: "CaribSea Bimini Pink ARAG-ALIVE! Saltwater Reef Substrate 10 lb or 20 lb",
    description: "Product Description: Qty: 1 10 or 20 lb bag You can now bring the world\u2019s most exotic reefs into your home with CaribSea\u2019s Arag-Alive!\u2122 substrates. Eight environmentally accurate ecoscapes, developed through CaribSea\u2019s cooperation with public aquariums and zoological parks where authenticity is a must, Arag-Alive!\u2122 makes any aquarium uniquely yours. Arag-Alive!\u2122 makes it easy to set up an aquarium. It\u2019s ready to work, clears quickly, and contains millions of live bacteria to cycle super fast and create a natural biological balance. Arag-Alive!\u2122 suppresses the dreaded \u201cnew tank syndrome\u201d, compresses the ammonia cycle, and discourages nuisance algae. Available options: 20 lb bag, 10 lb bag. Listed price is for 20 lb bag.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 37.99,
    wholesalePrice: 28.49,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "caribsea-dragon-stone-aquascaping-exotica-freshwater-aquarium-rock-25lbs",
    name: "CaribSea Dragon Stone Aquascaping Exotica Freshwater Aquarium Rock 25lbs.",
    description: "Product Description: Qty: (1) 25lb box EXOTICA FRESHWATER ROCK Bold and Beautiful. Exotica\u2122, the new freshwater rock line from CaribSea. Specially selected from around the world, these dramatic stones are the backdrop of the most spectacular freshwater aquascapes. All natural, no paints, dyes, or plastic coatings. Use with our Super Naturals\u2122, Eco-Complete\u2122, Instant Aquarium\u2122, or Samurai Soil\u2122 to create strikingly beautiful freshwater aquascapes.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 69.99,
    wholesalePrice: 52.49,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate & hardscape", "equipment", "dry goods"],
  },
  {
    id: "caribsea-fiji-pink-arag-alive-live-sand-10-or-20lb-reef-substrate-aquarium-saltwater",
    name: "CaribSea Fiji Pink ARAG-ALIVE! Live Sand, 10 or 20lb Reef Substrate Aquarium Saltwater",
    description: "Product Description: Qty: 1 Sizes 10lb or 20lb bags You can now bring the world\u2019s most exotic reefs into your home with CaribSea\u2019s Arag-Alive!\u2122 substrates. Eight environmentally accurate ecoscapes, developed through CaribSea\u2019s cooperation with public aquariums and zoological parks where authenticity is a must, Arag-Alive!\u2122 makes any aquarium uniquely yours. Arag-Alive!\u2122 makes it easy to set up an aquarium. It\u2019s ready to work, clears quickly, and contains millions of live bacteria to cycle super fast and create a natural biological balance. Arag-Alive!\u2122 suppresses the dreaded \u201cnew tank syndrome\u201d, compresses the ammonia cycle, and discourages nuisance algae. Available options: 20 lb bag, 10 lb bag. Listed price is for 20 lb bag.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 39.99,
    wholesalePrice: 29.99,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "caribsea-rio-grande-freshwater-substrate-super-natural-5-or-20-lb",
    name: "CaribSea Rio Grande Freshwater Substrate Super Natural 5 or 20 lb",
    description: "Product Description: Qty: 1 Sizes: 5lb or 20 lb bag SUPER NATURALS Create a supernatural experience by re-creating the natural world in your home. Enjoy a piece of the Rio Negro as it winds its way through dark and brooding jungles. Own a sliver of the sunlit Sri Lankan gravel streams famous for sapphires and rubies. Dramatic black sand rivers and beaches grace the flanks of verdant tropical islands capped by smoldering volcanoes. These exotic locales provide the backdrop for some of the world\u2019s most spectacular aquatic life. The Super Naturals line is specially selected and crafted to match these exotic environments. Available options: 5 lb bag, 20 lb bag. Listed price is for 5 lb bag.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 25.99,
    wholesalePrice: 19.49,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "caribsea-samurai-soil-substrate-for-shrimp-and-planted-aquaria",
    name: "CaribSea Samurai Soil Substrate for shrimp and planted aquarium",
    description: "Product Description: Qty: 1 9lb container Caribsea Samurai Soil is the ideal substrate for shrimp and planted aquaria. This unique, uniformly graded material fits the pH and mineral requirements of the most sensitive freshwater fauna and flora, without the muddy texture and crumbling often seen with other brands. Typical Size: 1 mm approximately",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 42.99,
    wholesalePrice: 32.24,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "caribsea-eco-complete-planted-freshwater-substrate-red",
    name: "CaribSea \u2013 ECO COMPLETE PLANTED Freshwater Substrate, Red",
    description: "Product Description: Typical Size: 3.0 - 6.0mmAverage Density: 54 pounds per cubic foot Color: Red Item: 20 lb bag ECO-COMPLETE\u2122 PLANTED The eco-Complete\u2019s\u2122 secret lies in rich basaltic volcanic soil which contains iron, calcium, magnesium, potassium, sulfur plus over 25 other elements to nourish your aquatic plants. Floraspore\u2122 symbionts activate the root-substrate interface to facilitate the uptake of minerals which make for a healthier root and healthier plant. Iron-rich Eco\u2011Complete\u2122 eliminates the need for laterite. No artificial dyes, paints, or chemical coatings.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 45.99,
    wholesalePrice: 34.49,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "caribsea-eco-complete-planted-freshwater-substrate-black",
    name: "CaribSea \u2013 ECO COMPLETE PLANTED Freshwater Substrate, Black",
    description: "Product Description: Please note: This listing has the option of a 10lb or 20lb bag. Specifications for 10lb bags: Typical Size: 0.25 - 7.0mmAverage Density: 27 pounds per cubic foot Specifications for 20lb bags: Typical Size: 0.25 - 7.0mmAverage Density: 54 pounds per cubic foot ECOCOMPLETE\u2122 PLANTED The Eco-Complete\u2019s\u2122 secret lies in rich basaltic volcanic soil which contains iron, calcium, magnesium, potassium, sulfur plus over 25 other elements to nourish your aquatic plants. Floraspore\u2122 symbionts activate the root-substrate interface to facilitate the uptake of minerals which make for a healthier root and healthier plant. Iron-rich Eco\u2011Complete\u2122 eliminates the need for laterite. Available options: 20lb bag, 10lb bag. Listed price is for 20lb bag.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 45.99,
    wholesalePrice: 34.49,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "caribsea-eco-complete-cichlid-zach-black",
    name: "CaribSea \u2013 ECO-COMPLETE CICHLID Zach Black 20 llb bag",
    description: "Product Description: Typical Size: 4.0 - 10.0mmAverage Density: 54 pounds per cubic footItem: 20 lb bag ECO-COMPLETE\u2122 CICHLID Maintains the high pH that African Cichlids need while helping to resist pH drops associated with Cichlid systems. It buffers automatically for the life of the aquarium. Contains live, water purifying bacteria that makes cycling a new aquarium faster and safer. No rinsing required! Eco\u2011Complete\u2122 is packed in a water conditioning solution for immediate results!",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 42.99,
    wholesalePrice: 32.24,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "caribsea-life-rock-frag-zone",
    name: "CaribSea \u2013 Life Rock Frag Zone",
    description: "Product Description: FRAGZONE\u2122 Get your frags seated faster on this preconditioned rubble! Package Sizes:1 box about 2 1/2 pounds Use: Marine and Reef Aquarium",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 29.99,
    wholesalePrice: 22.49,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate & hardscape", "equipment", "dry goods"],
  },
  {
    id: "caribsea-liferock-for-aquascapes-and-reefs-20-lb-box",
    name: "CaribSea \u2013 LifeRock for Aquascapes and Reefs (20 lb box)",
    description: "Product Description: LifeRock\u2122 begins as a sunlit piece of Pleistocene era seafloor thriving with living creatures. Over the next 100 millennia and the retreat of the ocean, this ancient piece of the seafloor, now well inland, has formed a pure, aragonite-bearing rock. This clean base rock is 97% calcium carbonate with minor and trace elements such as strontium, magnesium, and barium. This base has an amazing 50% void space which will provide residence for billions of water-purifying bacteria. LifeRock\u2122 is infused with bacteria using AragAlive\u2122 technology which results in a reduction of traditional cycling times.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 99.99,
    wholesalePrice: 74.99,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate & hardscape", "equipment", "dry goods"],
  },
  {
    id: "caribsea-mountain-stone-seiryu-stone-black-5-lbs",
    name: "CaribSea \u2013 Mountain Stone/Seiryu Stone, Black",
    description: "Product Description: EXOTICA\u2122 FRESHWATER ROCK Bold and Beautiful. Exotica\u2122, the new freshwater rock line from CaribSea. Specially selected from around the world, these dramatic stones are the backdrop of the most spectacular freshwater aquascapes. All-natural, no paints, dyes, or plastic coatings. Use with our Super Naturals\u2122, Eco-Complete\u2122, Instant Aquarium\u2122, or Samurai Soil\u2122 to create strikingly beautiful freshwater aquascapes. Please see our other listings for great prices and customer service! We offer free shipping and buy 2 get 1 FREE on all items with (BUY 2 GET 1 FREE) in the title How BOGO works? Available options: 5 lbs, 10lbs, 15 lbs, 20 lbs, 25 lbs. Listed price is for 5 lbs.",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 22.99,
    wholesalePrice: 17.24,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["caribsea", "stone"],
  },
  {
    id: "caribsea-eco-complete-cichlid-freshwater-substrate-white",
    name: "CaribSea-Eco Complete Cichlid Freshwater Substrate, White 20 lb bag",
    description: "Product Description: Typical Size: 0.5 - 1.5mm Average Density: 54 pounds per cubic foot Color: White Item: 20 lb bag ECO-COMPLETE\u2122 CICHLID Maintains the high pH that African Cichlids need while helping to resist pH drops associated with Cichlid systems. It buffers automatically for the life of the aquarium. Contains live, water purifying bacteria that makes cycling a new aquarium faster and safer. No rinsing required! Eco\u2011Complete\u2122 is packed in a water conditioning solution for immediate results!",
    category: "Dry Goods",
    subCategory: "Substrate & Hardscape",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 49.99,
    wholesalePrice: 37.49,
    imageGradient: "from-stone-700 to-slate-900",
    tags: ["substrate"],
  },
  {
    id: "cichlid-sinking-gold-mini-12-oz",
    name: "Cichlid Sinking Gold - Mini - 12 oz.",
    description: "Key feature: Great for larger tropical fish also Description: HIKARI SALES USA INC - HIKARI SINK CICHLID MINI 12OZ. Sinking Pellet That Will Not Cloud The Water Allows easy monitoring of amount eaten Helps eliminate over-feeding Reduces water quality problems More Economical Color Enhancement High In Astaxanthin Brings Out Natural, Brilliant Colors Reduces Washed Out Colors Contains Stabilized Vitamin C Promotes resistance to stress Promotes resistance to infectious disease Promotes a long, healthy life Excellent Daily Diet Outstanding nutrition High protein levels Improved growth rates Great for larger tropical fish also",
    category: "Dry Goods",
    subCategory: "Food & Nutrition",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 19.99,
    wholesalePrice: 14.99,
    imageGradient: "from-amber-800 to-orange-950",
    tags: ["food & nutrition", "equipment", "dry goods"],
  },
  {
    id: "coral-rx-8oz-coral-dip",
    name: "Coral RX 8oz Coral Dip",
    description: "Key Features: Well-mixed, Produces twelve gallons with eight ounce bottle Natural ingredients that contain no iodine or oxidizers, which is harmful and toxic to corals Coral Rx can treat many types of live corals, SPS, and LPS Item Package weight : 1.0 pounds Description:Coral Rx was designed with the health of your corals in mind. The proprietary blend of natural ingredients contains no iodine, which is known to stain corals, nor does Coral Rx contain oxidizers whose by-products are often toxic and continue to react with surrounding tissue. Coral Rx removes many of the \"hard to deal with\" coral pests like Flatworms, and coral/polyp eating Nudibranchs.",
    category: "Dry Goods",
    subCategory: "Water Treatment",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 24.99,
    wholesalePrice: 18.74,
    imageGradient: "from-teal-800 to-slate-900",
    tags: ["water treatment", "equipment", "dry goods"],
  },
  {
    id: "coral-rx-pro-concentated-coral-dip-1oz",
    name: "Coral RX Pro- Concentated Coral Dip 1oz",
    description: "Key Features: For each gallon of saltwater from aquarium use 30 drops of Coral Rx Pro Effective in treating corals with parasites and bacterial infections Treats coral pests, flatworms, bristleworms, and red flatworms Description: Coral Rx was designed with the health of your corals in mind. The proprietary blend of natural ingredients contains no iodine, which is known to stain corals, nor does Coral Rx contain oxidizers whose by-products are often toxic and continue to react with surrounding tissue. Coral Rx removes many of the \"hard to deal with\" coral pests like Flatworms, and coral/polyp eating Nudibranchs.",
    category: "Dry Goods",
    subCategory: "Water Treatment",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 24.99,
    wholesalePrice: 18.74,
    imageGradient: "from-teal-800 to-slate-900",
    tags: ["water treatment", "equipment", "dry goods"],
  },
  {
    id: "green-goddess-concentrated-liquid-fertilizer-easy-to-dose-all-in-one-supplement-for-freshwater-aquariums-promotes-healthy-plant-growth-ideal-for-low-to-moderate-tech-tanks",
    name: "Green Goddess Concentrated Liquid Fertilizer - Easy to Dose All-in-One Supplement for Freshwater Aquariums - Promotes Healthy Plant Growth - Ideal for Low to Moderate Tech Tanks",
    description: "Green Goddess Concentrated Liquid Fertilizer Transform your freshwater aquarium into a lush, vibrant aquatic paradise with Green Goddess, the ultimate concentrated liquid fertilizer. Designed for both novice and experienced aquarists, our easy-to-dose formula provides all the essential nutrients your plants need for healthy, vigorous growth. Concentrated Formula Our highly concentrated formula means a little goes a long way, making Green Goddess an economical choice for any aquarium. Just a few drops will provide your plants with the nutrients they need to thrive. Easy to Dose Green Goddess is designed for ease of use. Available options: 4 ounce, 8 ounce. Listed price is for 4 ounce.",
    category: "Dry Goods",
    subCategory: "Equipment",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 19.99,
    wholesalePrice: 14.99,
    imageGradient: "from-slate-700 to-slate-950",
    tags: ["aquascapes", "low-light plants", "medium-light"],
  },
  {
    id: "hydor-seltz-d-dc-500-750-or-1000-controllable-universal-water-pump-for-salt-and-freshwater-aquarium",
    name: "Hydor Seltz D DC 500, 750 or 1000 Controllable Universal Water Pump for Salt and Freshwater Aquarium",
    description: "Product Description: Qty: 1 Seltz D DC is a multipurpose electronic universal pump, designed for energy savings.Water flow is adjusted by the included electronic controller.The Hydor Seltz D DC pumps are ideal for sumps, refugiums, biological filters, and in the general circulation of freshwater or saltwater aquariums to benefit the ecosystem's health. Seltz D DC is equipped with pre-filter and barbed pipe fitting for various sized hoses. The Seltz D DC is perfectly suited for all applications that require submerged or in-line installation of the pump. Available options: 500, 750, 1000. Listed price is for 500.",
    category: "Dry Goods",
    subCategory: "Pumps & Flow",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 115.99,
    wholesalePrice: 86.99,
    imageGradient: "from-slate-700 to-blue-900",
    tags: ["aquascapes", "ecoscapes", "freshwater", "saltwater"],
  },
  {
    id: "icecap-2k-gyre-flow-pump-with-dual-pump-wifi-controller",
    name: "IceCap 2K Gyre Flow Pump With WaveEngine LE WiFi Controller",
    description: "Product Description: Qty: 1 Max Flow 2,000gph | 8~25 watts | 20-90+ gallonsIncludes 2K Gyre Pump, power supply and WaveEngine LE WiFi ControllerApplicable for glass or acrylic aquariums up to 1/2 in thick. The IceCap Gyre is back and better than ever! The all-new IceCap 2K Gyre Flow Pump is not only more powerful than its predecessor, it is now WiFi controllable, allowing you to fine-tune your flow effortlessly and wirelessly from your mobile device.",
    category: "Dry Goods",
    subCategory: "Pumps & Flow",
    waterType: "Saltwater",
    availability: "OUT OF SEASON",
    price: 299.99,
    wholesalePrice: 224.99,
    imageGradient: "from-slate-700 to-blue-900",
    tags: ["air pump", "aquascapes", "ecoscapes", "freshwater", "reef", "saltwater"],
  },
  {
    id: "icecap-4k-gyre-flow-pump-with-dual-pump-wifi-controller",
    name: "ICECAP 4K GYRE FLOW PUMP WITH WAVEENGINE LE CONTROLLER",
    description: "Product Description: Qty: 1 Max Flow 4,000gph | 13~45 watts | 25-150+ gallonsIncludes 4K Gyre, PSU, & Dual Pump WiFi ControllerApplicable for glass or acrylic aquariums up to 5/8 in thick The IceCap Gyre is back and better than ever! The all-new IceCap 4K Gyre Flow Pump is not only more powerful than its predecessor, it is now WiFi controllable, allowing you to fine-tune your flow effortlessly and wirelessly from your mobile device. The IceCap 4K Gyre uses officially licensed technology by Maxspect, creators of the original Gyre pump, to generate the now-iconic gyre water flow in your aquarium\u2014but without breaking the bank!",
    category: "Dry Goods",
    subCategory: "Pumps & Flow",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 329.99,
    wholesalePrice: 247.49,
    imageGradient: "from-slate-700 to-blue-900",
    tags: ["air pump", "aquascapes", "ecoscapes", "freshwater", "reef", "saltwater"],
  },
  {
    id: "icecap-di-media-color-indicating-mized-bed-deionization-resin-1-25-lbs",
    name: "IceCap DI Media Color indicating mixed bed deionization resin 1.25 lbs.",
    description: "Product Description: Qty: (1) 1.25 lbs bag single fill DI filter is the last stage of water filtration for the Smart RODI reverse osmosis systems and is necessary to reduce Total Dissolved Solids (TDS) to zero.",
    category: "Dry Goods",
    subCategory: "Water Treatment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 19.99,
    wholesalePrice: 14.99,
    imageGradient: "from-teal-800 to-slate-900",
    tags: ["water treatment", "equipment", "dry goods"],
  },
  {
    id: "ista-bio-sponge-round-bio-foam-large",
    name: "Ista - Bio Sponge - Round Bio Foam - Large",
    description: "Key Features: Provides excellent filtering effect while oxygenating the water Can be used with either an air pump or any external filter Easy to install and simple to maintain Description: \ufeffProvides excellent filtering effect while oxygenating the water. Can be used with either an air pump or any external filter. Easy to install and simple to maintain.",
    category: "Dry Goods",
    subCategory: "Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 15.99,
    wholesalePrice: 11.99,
    imageGradient: "from-slate-700 to-slate-950",
    tags: ["equipment", "equipment", "dry goods"],
  },
  {
    id: "ista-2-in-1-co2-bubble-counter-with-check-valve",
    name: "ISTA 2 IN 1 CO2 BUBBLE COUNTER WITH CHECK VALVE",
    description: "Item is easy to install. The hose mechanism is quite simple (similar to canister filters), it\u00b4s perfect to use with the MAX MIX CO2 REACTOR because it allows to control the CO2 flow, once it\u00b4s impossible to control the CO2 flow using only the reactor. CHARACTERISTICS: 2 in 1 function: CO2 bubble counter and check valve. CO2 pipe fasten screw node provided to assure burst out of the CO2 pipe. Spring type check valve is the best in preventing backflow. Acrylic material provides clear and easy bubble reading. Acid and break-resistant. Easy disassembling of the cap in filling up water.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 12.99,
    wholesalePrice: 9.74,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["bubble counter", "check valve", "co2", "ista", "water plant"],
  },
  {
    id: "ista-acu-dose-co2-pressure-regulator-360-rotatable-outlet",
    name: "ISTA ACU-DOSE CO2 PRESSURE REGULATOR (360\u00b0 ROTATABLE OUTLET)",
    description: "The best one you can find. Extremely precise, this regulator can be set for even 1 bubble at each 5 \u2013 8 seconds. It\u00b4s extremely easy to regulate the CO2 flow. CHARACTERISTICS: Easy assembling: no tools required for attaching to the CO2 cylinder. An extremely precise needle valve assures accurate and reliable dosing. One stage pressure reduced to assure constant and reliable CO2 dosing. 360\u00b0 adjustable CO2 outlet provides convenient Co2 system set up",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 58.99,
    wholesalePrice: 44.24,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["bubble counter", "co2", "co2 diffuser", "ista", "live plants", "regulator"],
  },
  {
    id: "ista-co2-45g-cartridge-supply-set",
    name: "ISTA CO2 45g CARTRIDGE SUPPLY SET",
    description: "ISTA CO2 45g CARTRIDGE SUPPLY SET. Condition New \u201cThe convenience of not having the hassle in refilling cylinders\u201d Ideal for Nano Tanks. These sets can be easily adapted to any kind of tank, even plug and play tanks. Ideal for beginners, and low light tanks, with low demands for CO2. The CO2 could last for months if set up correctly. For low light tanks, the rate of 1 bubble every 5 seconds can guarantee the usage for months. Place the CO2 diffuser to the very bottom of the tank to achieve the best CO2 diffusing effect. Convenient to use, and easy to install. The stylish supporting rack which brings additional elegancy to your aquarium set up.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 49.99,
    wholesalePrice: 37.49,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["aquascapes", "co2", "ecoscapes", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-co2-88g-cartridge-supply-set",
    name: "ISTA CO2 88G CARTRIDGE SUPPLY SET",
    description: "The convenience of not having the hassle of refilling cylinders! Ideal for Nano Tanks. These sets can be easily adapted to any kind of tank, even plug and play tanks. Ideal for beginners, and low light tanks, with low demands for CO2. The CO2 could last for months if set up correctly. For low light tanks, the rate of 1 bubble every 5 seconds can guarantee the usage for months. Place the CO2 diffuser to the very bottom of the tank to achieve the best CO2 diffusing effect. CHARACTERISTICS\uff1a Disposable CO2 cartridge makes it convenient for not having the hassle of refilling it. Supporting rack included which provides elegance and easy installation.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 59.99,
    wholesalePrice: 44.99,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["bubble counter", "co2", "co2 diffuser", "ista", "live plants", "regulator"],
  },
  {
    id: "ista-co2-95g-disposable-cartridge-supply-set-basic",
    name: "ISTA CO2 95G DISPOSABLE CARTRIDGE SUPPLY SET \u2013 BASIC",
    description: "\u201cThe convenience of not having the hassle in refilling cylinders\u201d Ideal for Nano Tanks. These sets can be easily adapted to any kind of tank, even plug and play tanks. Ideal for beginners, and low light tanks, with low demands for CO2. The CO2 could last for months if set up correctly. For low light tanks, the rate of 1 bubble every 5 seconds can guarantee the usage for months. Place the CO2 diffuser to the very bottom of the tank to achieve the best CO2 diffusing effect. CHARACTERISTICS\uff1a Disposable CO2 cartridge makes it convenient for not having the hassle of refilling it. Supporting rack included which provides elegance and easy installation.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 79.99,
    wholesalePrice: 59.99,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["bubble counter", "co2", "co2 diffuser", "ista", "live plants", "regulator"],
  },
  {
    id: "ista-co2-controller-mini-gauge-vertical",
    name: "ISTA CO2 CONTROLLER \u2013 MINI GAUGE \u2013 VERTICAL",
    description: "CHARACTERISTICS: Compact in size only compatible with the disposable CO2 Cartridge. Easy assembling: No tools required in fastening to the CO2 cartridge. One stage pressure reduced to assure constant reliable CO dosing.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 129.99,
    wholesalePrice: 97.49,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["bubble counter", "co2", "co2 diffuser", "ista", "live plants", "regulator"],
  },
  {
    id: "ista-co2-diffuser-3-in-1",
    name: "ISTA CO2 DIFFUSER \u2013 3 IN 1",
    description: "There are two options to chose from: Small and Large These are the most practical diffusers available. Into a single piece, you have a check valve, a bubble counter, and the diffuser. Also very important is that the ceramic plate can be replaced. CHARACTERISTICS: 3 functions in one unit: CO2 bubble counter, check valve, and diffuser. Produces bubbles as small as a mist of CO2, generating maximum possible diffusion on CO2 in the aquarium. Undisputable quality and reliability. Compact size. Easy to install. Available options: SMALL, LARGE. Listed price is for SMALL.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 14.5,
    wholesalePrice: 10.88,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["check valve", "co2", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-co2-indicator-solution",
    name: "ISTA CO2 INDICATOR SOLUTION",
    description: "CHARACTERISTICS: BOTTLE HOLDS 10CC Simply inject 1CC of CO2 Indicator solution into the cap of CO2 indicator. Adding aquarium water is not necessary. Recommended to be changed only once a month. Not necessary to change the solution every time maintenance is done to the aquarium.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 9.99,
    wholesalePrice: 7.49,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["co2", "indicator solution", "ista", "live plants", "water plant"],
  },
  {
    id: "co2-indicator-all-angle-view",
    name: "ISTA CO2 INDICATOR \u2013 ALL ANGLE VIEW",
    description: "CHARACTERISTICS: (Package includes: CO2 indicator, CO2 indicator solution, and Color chart) Allows you to monitor the CO2 level in your tank from any angle. Unique design prevents any chance of spilling the indicator solution. A reusable color chart sticker allows the constant repositioning of the position of the label on the aquarium.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 16.99,
    wholesalePrice: 12.74,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["co2", "indicator solution", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-disposable-co2-can-3-piece",
    name: "ISTA DISPOSABLE CO2 CAN (3 PIECE)",
    description: "Replacement CO2 canister to ISTA CO2 Diffuser Set (3 PIECE) Description: Contains 5500 ccs of CO2 gas (at 1 ATM 77 Degrees Fahrenheit) SAFETY CAUTION: Avoid exposure to direct sunlight.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 24.99,
    wholesalePrice: 18.74,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["bubble counter", "co2", "co2 diffuser", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-disposable-co2-cartridge-88g",
    name: "ISTA DISPOSABLE CO2 CARTRIDGE / 95G",
    description: "CHARACTERISTICS: Contains 95g of pressurized liquid CO2. The full weight of pressurized liquid CO2 assured for the best value compared to other existing similar cartridges in the market. Strict quality control and safety guaranteed. Disposable cartridge, free from the trouble of CO2 refilling. Simple and easy to replace the cartridge.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 19.99,
    wholesalePrice: 14.99,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["bubble counter", "co2", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-metal-air-valve-2-3-4-or-5-gang",
    name: "ISTA METAL AIR VALVE \u2013 (2, 3, 4, OR 5 GANG)",
    description: "Product Features: ( NOTE: THERE ARE 4 VERSIONS: 2, 3, 4, OR 5 GANG VALVES) Made by copper electroplating process, rust-resistant. Can be hung on the side of the fish tank. Provides several flow outputs from a single input. Each output may be adjusted accordingly. If the flow input is strong enough, the Metal Air Valve can be connected with more outputs. Available options: 5 GANG OUTPUT, 4 GANG OUTPUT, 3 GANG OUTPUT, 2 GANG OUTPUT. Listed price is for 5 GANG OUTPUT.",
    category: "Dry Goods",
    subCategory: "Accessories",
    waterType: "Both",
    availability: "OUT OF SEASON",
    price: 12.99,
    wholesalePrice: 9.74,
    imageGradient: "from-slate-600 to-slate-900",
    tags: ["air pump", "air stone", "air valve", "co2", "live plants"],
  },
  {
    id: "ista-mini-ceramic-co2-diffuser-cone",
    name: "ISTA MINI CERAMIC CO2 DIFFUSER \u2013 CONE",
    description: "The small size and stylish glass design will make this perfect for nano tanks. CHARACTERISTICS: Top-quality ceramic assures the best diffusing effect. 2 in 1 function: CO2 bubble counter and diffuser. The unit comes apart for easy ceramic replacement, cleaning, and water filling. Acrylic material provides clear CO2 bubble reading and also acid and break-resistant. CO2 pipe holder included to prevent CO2 pipe from bending.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 12.5,
    wholesalePrice: 9.38,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["co2", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-mini-co2-bubble-counter",
    name: "ISTA MINI CO2 BUBBLE COUNTER",
    description: "CHARACTERISTICS: Compact in size and crystal clear acrylic makes it unnoticeable. Elegant design adds a graceful touch to your CO2 supply system. Strict quality control assures no leakage.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 7.5,
    wholesalePrice: 5.62,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["bubble counter", "co2", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-planaria-trap",
    name: "ISTA PLANARIA TRAP",
    description: "Characteristics: A device used to Trap/Catch organisms such as Planaria, Flat Worms, and Leeches. Directions: Switch off lighting during planaria trapping. Put bait food in the pen and place the pen flatly to the gravel. Push the pen a little further down into the gravel to prevent shrimplets from entering.",
    category: "Dry Goods",
    subCategory: "Accessories",
    waterType: "Both",
    availability: "OUT OF SEASON",
    price: 28.5,
    wholesalePrice: 21.38,
    imageGradient: "from-slate-600 to-slate-900",
    tags: ["ista", "live plants", "trap", "water plant"],
  },
  {
    id: "replacement-ceramic-ufo-co2-diffuser",
    name: "ISTA REPLACEMENT CERAMIC (UFO CO2 DIFFUSER)",
    description: "Characteristics: Replacement Ceramic for UFO CO2 Diffuser Item #505",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 6.49,
    wholesalePrice: 4.87,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["co2", "co2 diffuser", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-spring-check-valve-for-co2-for-air-pump-applications",
    name: "ISTA SPRING CHECK VALVE FOR CO2 FOR AIR PUMP APPLICATIONS",
    description: "New Ista spring check valve Stainless spring design assures reliable prevention of backflow and siphoning. The check valve has minimal impact on the air pump and CO2 injection applications. Elegant in shape. Easy to disassemble for cleaning. Air tube fastening node assures no bursting of air tube.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 8.99,
    wholesalePrice: 6.74,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["air pump", "co2", "ista", "water plant"],
  },
  {
    id: "ista-ufo-co2-diffuser",
    name: "ISTA UFO CO2 DIFFUSER",
    description: "CHARACTERISTICS: Specific ceramic applied to assures the most delicate CO2 diffusing effect. The top-quality design allows the replacement of the diffusing ceramic; therefore eliminating the clogging problem. CO2 pipe can be fastened to the diffuser in a vertical position. This way, it prevents the pipe from bending which restricts the flow of CO2. Elegant in design. To have the best diffusing effect, place the diffuser in the very bottom of the tank, which will maximize the CO2 diffusion in water (creates more contact time of CO2 bubbles with surrounding water) The silicone suction cup assures long-lasting function.",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 13.5,
    wholesalePrice: 10.12,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["co2", "co2 diffuser", "ista", "live plants", "water plant"],
  },
  {
    id: "ista-replacement-co2-diffuser-ceramic-fits-3-in-1-small-co2-diffuser-and-mini",
    name: "ISTA \u2013 Replacement CO2 Diffuser Ceramic (fits 3-in-1 small CO2 diffuser and mini)",
    description: "Characteristics: This is a replacement ceramic diffuser element. This fits the following ISTA products: (fits 3-in-1 small CO2 diffuser and mini ceramic CO2 diffuser)",
    category: "Dry Goods",
    subCategory: "CO2 Equipment",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 5.95,
    wholesalePrice: 4.46,
    imageGradient: "from-slate-700 to-emerald-900",
    tags: ["check valve", "co2", "ista", "live plants", "water plant"],
  },
  {
    id: "klir-fleece-roller-filter-di-4",
    name: "Klir Fleece Roller Filter Di 4",
    description: "Enjoy a maintenance-free aquarium filtration for months at a time. Klir Filter 4in automatically unrolls new filtering material, removing suspended particles from your aquarium and producing crystal clear water. Modular Mechanical Filtration at its Finest. Product Description: The Patent Pending Klir Fleece Filter Di-4 fits directly into most 4 in filter sock chambers. This filter automatically unrolls new material as it gets clogged, removing suspended particles from your aquarium and producing crystal clear water. Enjoy maintenance-free aquarium filtration for months at a time. The Klir filter is a direct replacement for filter socks on sumps with sock trays.",
    category: "Dry Goods",
    subCategory: "Filtration",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 249.99,
    wholesalePrice: 187.49,
    imageGradient: "from-slate-700 to-cyan-900",
    tags: ["filtration", "equipment", "dry goods"],
  },
  {
    id: "phyto-feast-concentrate-32-oz",
    name: "Phyto Feast Concentrate - 6oz, 16oz, and 32oz",
    description: "A blend of the 5 marine microalgae most commonly used by universities and hatcheries for their superior nutritional value for aquaculturing marine species of all kinds: Pavlova, Isochrysis, Thalassiosira weissflogii, Tetraselmis, Nannochloropsis, and Synechococcus. Super-nutritious food for filter feeders including corals, Tridacnid clams, scallops, feather dusters, tunicates and zooplankton. Particle size: 1-15 microns. Available options: 32 oz, 16 oz, 6 oz. Listed price is for 32 oz.",
    category: "Dry Goods",
    subCategory: "Food & Nutrition",
    waterType: "Both",
    availability: "AVAILABLE",
    price: 45.99,
    wholesalePrice: 34.49,
    imageGradient: "from-amber-800 to-orange-950",
    tags: ["food & nutrition", "equipment", "dry goods"],
  },
  {
    id: "pond-scum-concentrated-liquid-fertilizer-easy-to-dose-all-in-one-supplement-for-freshwater-aquariums-promotes-healthy-plant-growth-ideal-for-low-to-moderate-light-tanks-and-4-ounce",
    name: "Pond Scum Concentrated Liquid Fertilizer - Easy to Dose All-in-One Supplement for Freshwater Aquariums - Promotes Healthy Plant Growth - Ideal for Low to Moderate Light Tanks and (4 ounce)",
    description: "Pond Scum Concentrated Liquid Fertilizer Transform your freshwater aquarium into a lush, vibrant aquatic paradise with Pond Scum, the ultimate concentrated liquid fertilizer. Designed for both novice and experienced aquarists, our easy-to-dose formula provides all the essential nutrients your plants need for healthy, vigorous growth. Concentrated Formula Our highly concentrated formula means a little goes a long way, making Pond Scum an economical choice for any aquarium. Just a few drops will provide your plants with the nutrients they need to thrive. Easy to Dose Pond Scum is designed for ease of use. Available options: 4 ounce, 8 ounce. Listed price is for 4 ounce.",
    category: "Dry Goods",
    subCategory: "Lighting",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 19.99,
    wholesalePrice: 14.99,
    imageGradient: "from-indigo-800 to-sky-900",
    tags: ["aquascapes", "low-light plants", "medium-light"],
  },
  {
    id: "seachem-impulse-multi-function-aquarium-water-pump-400-600-or-800",
    name: "Seachem Impulse Multi-Function Aquarium Water Pump 400, 600, or 800",
    description: "Product Description: Qty: (1) pump Sizes: 400, 600, or 800 The Impulse is a quiet, energy-efficient, multi-function pump. It is ideal for fresh and saltwater aquariums, protein skimmers, indoor fountains, water-cooling and all similar submersible and inline applications which require energy efficient, ultra quiet performance. The Impulse is equipped with a synchronous motor and an advanced impeller, ceramic shaft and bearings (stainless steel on the Impulse 400), and an adjustable flow rate. Multi-size hose adapter fittings and suction cups are included. Available options: Impulse 400 pump, Impulse 600 pump, Impulse 800 pump. Listed price is for Impulse 400 pump.",
    category: "Dry Goods",
    subCategory: "Pumps & Flow",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 92.89,
    wholesalePrice: 69.67,
    imageGradient: "from-slate-700 to-blue-900",
    tags: ["freshwater", "saltwater", "water quality"],
  },
  {
    id: "shore-aquatic-hemigraphis-repanda-bundle-live-aquarium-plant-tropical-freshwater-decorations-pest-free-great-for-starter-tanks",
    name: "Shore Aquatic Hemigraphis Repanda Bundle Live Aquarium Plant Tropical Freshwater Decorations- Pest free, great for starter tanks",
    description: "Hemigraphis repanda Hemigraphis repanda is best used as a terrarium and aquarium plant. Striking purple colors and narrow leaves create an interesting plant overall. Sometimes referred to as Dragon Flame, Hemigraphis repanda is sometimes incorrectly submerged in an aquarium environment for short periods of time. Common Name: Dragon flame Family Name: Acanthaceae Native To: Hybrid Lighting: Moderate Requirements: Should be used as a terrestrial/aquarium plant Growth Form: Spreading Growth Rate: Moderate True Aquatic: Terrarium/Aquarium plant Placement in Tank: Mid-ground Available As: Bunch",
    category: "Dry Goods",
    subCategory: "Decor",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 21.99,
    wholesalePrice: 16.49,
    imageGradient: "from-stone-700 to-amber-950",
    tags: ["decor", "equipment", "dry goods"],
  },
];
