// Livestock — freshwater invertebrates and fish
// Mystery snails (Pomacea bridgesii / Pomacea diffusa) are peaceful algae-grazing
// freshwater snails that breathe air via a siphon. Adults reach ~1.5–2 inches.
// All listings are juvenile/sub-adult sizes (~0.5–1 inch) for safe shipping.
import type { Product } from "./mockData";

const MYSTERY_SNAIL_BASE_DESC =
  "Mystery snails are peaceful, hardy algae grazers that won't harm plants or fry. They breathe air via a siphon so they need a tight-fitting lid and ~1 inch of headspace above the waterline. Keep in pH 7.0–8.4 with calcium-rich water (or a cuttlebone) to support strong shell growth. Compatible with community fish, shrimp, and other peaceful tankmates. Ships as juveniles roughly 1/2 to 1 inch in shell diameter — they grow fast and reach full size in a few months.";

export const livestockProducts: Product[] = [
  // ---- ASSORTED MULTI-PACKS ----
  {
    id: "ls-snail-assorted-3",
    name: "Mystery Snails — 3 Pack (Assorted Colors)",
    scientificName: "Pomacea bridgesii",
    description:
      "A surprise 3-pack of mystery snails — colors selected randomly from current stock and may include gold, blue, ivory, purple, black, magenta, or wild-type brown. Perfect for adding a pop of color and natural algae control to your tank. " +
      MYSTERY_SNAIL_BASE_DESC,
    category: "Livestock",
    subCategory: "Snails",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 24.99,
    size: "Juvenile, ~1/2–1 inch",
    wholesalePrice: 6.0,
    imageGradient: "from-amber-900 to-orange-900",
    tags: [
      "mystery snail",
      "snail",
      "livestock",
      "freshwater",
      "algae eater",
      "assorted",
      "peaceful",
      "beginner",
      "plant safe",
    ],
  },
  {
    id: "ls-snail-assorted-10",
    name: "Mystery Snails — 10 Pack (Assorted Colors)",
    scientificName: "Pomacea bridgesii",
    description:
      "A 10-pack of mystery snails for serious algae control or for stocking a larger tank — colors selected randomly from current stock and may include gold, blue, ivory, purple, black, magenta, or wild-type brown. Per-snail price drops significantly compared to the 3-pack. " +
      MYSTERY_SNAIL_BASE_DESC,
    category: "Livestock",
    subCategory: "Snails",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 59.99,
    size: "Juvenile, ~1/2–1 inch",
    wholesalePrice: 20.0,
    imageGradient: "from-amber-900 to-orange-900",
    tags: [
      "mystery snail",
      "snail",
      "livestock",
      "freshwater",
      "algae eater",
      "assorted",
      "bulk",
      "10 pack",
      "peaceful",
    ],
  },

  // ---- SINGLE-COLOR 3-PACKS ----
  {
    id: "ls-snail-gold-3",
    name: "Gold Mystery Snails — 3 Pack",
    scientificName: "Pomacea bridgesii",
    description:
      "Three bright gold/yellow mystery snails — the most iconic color in the hobby. The vivid golden shell pops against dark substrate and planted backgrounds, and the lemon-yellow foot is striking when extended. " +
      MYSTERY_SNAIL_BASE_DESC,
    category: "Livestock",
    subCategory: "Snails",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 24.99,
    size: "Juvenile, ~1/2–1 inch",
    wholesalePrice: 6.0,
    imageGradient: "from-yellow-700 to-amber-800",
    tags: [
      "mystery snail",
      "snail",
      "livestock",
      "freshwater",
      "algae eater",
      "gold",
      "yellow",
      "peaceful",
      "plant safe",
    ],
  },
  {
    id: "ls-snail-black-3",
    name: "Black Mystery Snails — 3 Pack",
    scientificName: "Pomacea bridgesii",
    description:
      "Three jet-black mystery snails — the darkest morph available and a striking contrast in planted tanks. The deep ebony shell and dark foot create a dramatic look against bright sand or green plants. " +
      MYSTERY_SNAIL_BASE_DESC,
    category: "Livestock",
    subCategory: "Snails",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 26.99,
    size: "Juvenile, ~1/2–1 inch",
    wholesalePrice: 7.0,
    imageGradient: "from-slate-900 to-zinc-950",
    tags: [
      "mystery snail",
      "snail",
      "livestock",
      "freshwater",
      "algae eater",
      "black",
      "peaceful",
      "plant safe",
    ],
  },
  {
    id: "ls-snail-blue-3",
    name: "Blue Mystery Snails — 3 Pack",
    scientificName: "Pomacea bridgesii",
    description:
      "Three blue mystery snails — silvery-blue shells with a pale, almost lavender foot. One of the most popular colors in the hobby and a striking centerpiece-quality invertebrate for any planted tank. " +
      MYSTERY_SNAIL_BASE_DESC,
    category: "Livestock",
    subCategory: "Snails",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 29.99,
    size: "Juvenile, ~1/2–1 inch",
    wholesalePrice: 8.0,
    imageGradient: "from-blue-900 to-cyan-900",
    tags: [
      "mystery snail",
      "snail",
      "livestock",
      "freshwater",
      "algae eater",
      "blue",
      "peaceful",
      "plant safe",
    ],
  },
  {
    id: "ls-snail-ivory-3",
    name: "Ivory Mystery Snails — 3 Pack",
    scientificName: "Pomacea bridgesii",
    description:
      "Three ivory white mystery snails — pure cream-white shells with a soft white foot. A clean, elegant look that pairs beautifully with dark substrate and vibrant red plants. " +
      MYSTERY_SNAIL_BASE_DESC,
    category: "Livestock",
    subCategory: "Snails",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 29.99,
    size: "Juvenile, ~1/2–1 inch",
    wholesalePrice: 8.0,
    imageGradient: "from-stone-300 to-amber-100",
    tags: [
      "mystery snail",
      "snail",
      "livestock",
      "freshwater",
      "algae eater",
      "ivory",
      "white",
      "peaceful",
      "plant safe",
    ],
  },
  {
    id: "ls-snail-purple-3",
    name: "Purple Mystery Snails — 3 Pack",
    scientificName: "Pomacea bridgesii",
    description:
      "Three premium purple mystery snails — deep magenta-burgundy shells with dramatic dark spiral banding. The most prized and rarest color in the hobby, with a striking pale yellow foot that contrasts vividly against the rich purple shell. " +
      MYSTERY_SNAIL_BASE_DESC,
    category: "Livestock",
    subCategory: "Snails",
    waterType: "Freshwater",
    availability: "AVAILABLE",
    price: 32.99,
    size: "Juvenile, ~1/2–1 inch",
    wholesalePrice: 9.5,
    imageGradient: "from-purple-900 to-fuchsia-900",
    tags: [
      "mystery snail",
      "snail",
      "livestock",
      "freshwater",
      "algae eater",
      "purple",
      "magenta",
      "premium",
      "peaceful",
      "plant safe",
    ],
  },

  // ─── Scarlet Hermit Crabs (Paguristes cadenati) — Saltwater Invertebrates ─────
  {
    id: "sw-hermit-scarlet-5",
    name: "Red Legged Scarlet Hermit Crabs — 5 Pack",
    scientificName: "Paguristes cadenati",
    description:
      "Sustainably sourced from our own Caribbean waters by certified collectors and acclimated at our licensed aquaculture facility before shipping. Peaceful reef-safe hermit crabs from the Caribbean — solid scarlet body with distinctive yellow eyestalks. Adults reach 1 to 1.5 inches. Opportunistic omnivore that forages biofilm and organic debris on mature surfaces. Suitable for established saltwater systems with corals, peaceful fish, and other invertebrates including seahorses. Recommended stocking: 1 crab per 2–3 gallons. Ships overnight in breathable bags with thermal insulation. Established saltwater tanks only (10+ gallons).",
    category: "Livestock",
    subCategory: "Saltwater Invertebrates",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 29.99,
    size: "Juvenile to sub-adult (0.5–1 in)",
    wholesalePrice: 7.0,
    imageGradient: "from-rose-900 to-red-950",
    tags: [
      "hermit crab",
      "scarlet hermit",
      "red legged hermit",
      "Paguristes cadenati",
      "saltwater",
      "reef safe",
      "invertebrate",
      "marine invertebrate",
      "peaceful",
      "caribbean",
      "sustainably sourced",
    ],
  },
  {
    id: "sw-hermit-scarlet-10",
    name: "Red Legged Scarlet Hermit Crabs — 10 Pack",
    scientificName: "Paguristes cadenati",
    description:
      "Sustainably sourced from our own Caribbean waters and acclimated at our licensed aquaculture facility before shipping. 10-pack of peaceful reef-safe Scarlet Hermits (Paguristes cadenati) — a Caribbean invertebrate species that forages biofilm and organic debris on mature aquarium surfaces. Ideal for 20–30 gallon reefs at 1 crab per 2–3 gallons. Solid red body, yellow eyestalks, adults reach 1 to 1.5 inches. Compatible with corals, peaceful fish, and other invertebrates including seahorses. Ships overnight in breathable bags with thermal insulation. Established saltwater systems only.",
    category: "Livestock",
    subCategory: "Saltwater Invertebrates",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 49.99,
    size: "Juvenile to sub-adult (0.5–1 in)",
    wholesalePrice: 12.0,
    imageGradient: "from-rose-900 to-red-950",
    tags: [
      "hermit crab",
      "scarlet hermit",
      "red legged hermit",
      "Paguristes cadenati",
      "saltwater",
      "reef safe",
      "invertebrate",
      "marine invertebrate",
      "peaceful",
      "caribbean",
      "10 pack",
      "bulk",
    ],
  },
  {
    id: "sw-hermit-scarlet-20",
    name: "Red Legged Scarlet Hermit Crabs — 20 Pack",
    scientificName: "Paguristes cadenati",
    description:
      "Sustainably sourced from our own Caribbean waters and acclimated at our licensed aquaculture facility before shipping. Bulk 20-pack of Scarlet Hermits (Paguristes cadenati) sized for larger reef systems — ideal for 40+ gallon displays at 1 crab per 2–3 gallons. Peaceful Caribbean invertebrate species — opportunistic omnivores that forage biofilm and organic debris on mature surfaces. Compatible with corals, peaceful community fish, and seahorses. Provide a shell bank of 3 to 5 spare empty shells per crab to support natural molting and growth. Ships overnight in breathable bags with thermal insulation.",
    category: "Livestock",
    subCategory: "Saltwater Invertebrates",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 89.99,
    size: "Juvenile to sub-adult (0.5–1 in)",
    wholesalePrice: 20.0,
    imageGradient: "from-rose-900 to-red-950",
    tags: [
      "hermit crab",
      "scarlet hermit",
      "red legged hermit",
      "Paguristes cadenati",
      "saltwater",
      "reef safe",
      "invertebrate",
      "marine invertebrate",
      "peaceful",
      "caribbean",
      "20 pack",
      "bulk",
      "premium",
    ],
  },
];
