// Saltwater Products — macroalgae, corals, marine plants, inverts
// Pricing matched to Top Shelf Aquatics (topshelfaquatics.com/collections/macroalgae)
import type { Product } from "./mockData";

export const saltwaterProducts: Product[] = [
  {
    id: "live-marine-rotifers",
    name: "Live Marine Rotifers",
    description:
      "Live, actively reproducing marine rotifer culture at 500–1,000 per mL. First food for clownfish and other marine larvae, plus corals, seahorses, pipefish, mandarins, and filter-feeding inverts. Ships in growing water — feed straight away or start your own culture. Available 1/2 gallon, 1 gallon, 2 gallon. Free local pickup or overnight/2-day shipping (cost baked into price).",
    category: "Saltwater",
    subCategory: "Live Food",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 75,
    size: "1/2 gallon – 2 gallon",
    wholesalePrice: 0,
    imageGradient: "from-cyan-900 to-teal-900",
    tags: [
      "rotifers",
      "live food",
      "marine",
      "saltwater",
      "reef",
      "fry food",
      "larval food",
      "clownfish",
      "coral food",
      "seahorse",
      "live culture",
      "zooplankton",
    ],
  },
  {
    id: "sw-chaeto",
    name: "Chaetomorpha Macroalgae",
    scientificName: "Chaetomorpha linum",
    description:
      "Hardy green macroalgae prized by reefkeepers for nutrient export. Pulls nitrates and phosphates from the water column while providing shelter for copepods and amphipods. Does best when tumbled in a refugium with ample water movement. Provide adequate lighting to thrive.",
    category: "Saltwater",
    subCategory: "Macroalgae",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 29.99,
    size: "Golf ball size",
    wholesalePrice: 12.0,
    imageGradient: "from-emerald-900 to-teal-900",
    tags: [
      "macroalgae",
      "saltwater",
      "reef",
      "refugium",
      "nutrient export",
      "nitrate",
      "phosphate",
      "chaeto",
      "pod habitat",
    ],
  },
  {
    id: "sw-redogo",
    name: "Red Ogo Gracilaria Macroalgae",
    scientificName: "Gracilaria parvispora",
    description:
      "Vibrant red macroalgae that doubles as a natural nutrient exporter and a premium food for tangs and other herbivores. Absorbs nitrates and phosphates from the water column while adding striking color to refugiums and display tanks. Provide moderate flow and adequate lighting.",
    category: "Saltwater",
    subCategory: "Macroalgae",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 29.99,
    size: "Golf ball size",
    wholesalePrice: 12.0,
    imageGradient: "from-red-900 to-rose-900",
    tags: [
      "macroalgae",
      "saltwater",
      "reef",
      "refugium",
      "red ogo",
      "gracilaria",
      "tang food",
      "nutrient export",
      "herbivore",
    ],
  },
  {
    id: "sw-pompom",
    name: "Pom Pom Gracilaria Macroalgae",
    scientificName: "Gracilaria hayi",
    description:
      "Ravenous consumer of nitrates, phosphates, and dissolved organic wastes. Its tightly branched, pom-pom structure resists biofouling and creates bioactive substrate for copepods, amphipods, and beneficial microbes. Tangs and rabbitfish will readily consume this nutritious macroalgae, making it an excellent dual-purpose choice for display tanks and refugiums alike.",
    category: "Saltwater",
    subCategory: "Macroalgae",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 19.99,
    size: "Small / Medium",
    wholesalePrice: 7.5,
    imageGradient: "from-rose-900 to-pink-900",
    tags: [
      "macroalgae",
      "saltwater",
      "reef",
      "refugium",
      "pom pom",
      "gracilaria",
      "tang food",
      "rabbitfish",
      "nutrient export",
      "pod habitat",
    ],
  },

  // ─── Scarlet Hermit Crabs (Paguristes cadenati) — Cleanup Crew ─────────
  {
    id: "sw-hermit-scarlet-5",
    name: "Red Legged Scarlet Hermit Crabs — 5 Pack",
    scientificName: "Paguristes cadenati",
    description:
      "Sustainably sourced from our own Caribbean waters by certified collectors and acclimated at our licensed aquaculture facility before shipping. Reef-safe hermit crabs prized for their peaceful temperament and unique appetite for cyanobacteria (red slime algae). They also graze hair algae, diatoms, detritus, and uneaten food while leaving corals, snails, and fish alone. Solid scarlet body with distinctive yellow eyestalks. Adults reach 1–1.5 inches. Stock 1 crab per 2–3 gallons for sustainable foraging. Ships overnight with live arrival guarantee. Established saltwater tanks only (10+ gallons).",
    category: "Saltwater",
    subCategory: "Invertebrates",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 29.99,
    size: "Juvenile to sub-adult (0.5–1 in)",
    wholesalePrice: 7.0,
    imageGradient: "from-rose-900 to-red-950",
    tags: [
      "hermit crab",
      "scarlet hermit",
      "red legged hermit",
      "Paguristes cadenati",
      "saltwater",
      "reef safe",
      "cleanup crew",
      "CUC",
      "invertebrate",
      "cyanobacteria",
      "algae eater",
      "peaceful",
    ],
  },
  {
    id: "sw-hermit-scarlet-10",
    name: "Red Legged Scarlet Hermit Crabs — 10 Pack",
    scientificName: "Paguristes cadenati",
    description:
      "Sustainably sourced from our own Caribbean waters and acclimated at our licensed aquaculture facility before shipping. 10-pack of reef-safe Scarlet Hermits (Paguristes cadenati) — peaceful Caribbean cleanup crew specialized in eating cyanobacteria (red slime), hair algae, diatoms, and detritus. Ideal for 20–40 gallon reefs at 1 crab per 2–3 gallons. Solid red body, yellow eyestalks, adults reach 1–1.5 inches. Reef-safe with corals, peaceful fish, and other inverts including seahorses. Ships overnight with live arrival guarantee. Established saltwater tanks only — never introduce to new systems.",
    category: "Saltwater",
    subCategory: "Invertebrates",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 49.99,
    size: "Juvenile to sub-adult (0.5–1 in)",
    wholesalePrice: 12.0,
    imageGradient: "from-rose-900 to-red-950",
    tags: [
      "hermit crab",
      "scarlet hermit",
      "red legged hermit",
      "Paguristes cadenati",
      "saltwater",
      "reef safe",
      "cleanup crew",
      "CUC",
      "invertebrate",
      "cyanobacteria",
      "10 pack",
      "bulk",
    ],
  },
  {
    id: "sw-hermit-scarlet-20",
    name: "Red Legged Scarlet Hermit Crabs — 20 Pack",
    scientificName: "Paguristes cadenati",
    description:
      "Sustainably sourced from our own Caribbean waters and acclimated at our licensed aquaculture facility before shipping. Bulk 20-pack of Scarlet Hermits (Paguristes cadenati) sized for larger reef systems — ideal for 50+ gallon displays at 1 crab per 2–3 gallons. Peaceful Caribbean species specialized in eating cyanobacteria (red slime), hair algae, diatoms, and detritus. Best per-crab price for serious cleanup crews. Reef-safe with corals, peaceful fish, and seahorses. Provide a shell bank of 3–5 spare empty shells per crab. Ships overnight with live arrival guarantee.",
    category: "Saltwater",
    subCategory: "Invertebrates",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 89.99,
    size: "Juvenile to sub-adult (0.5–1 in)",
    wholesalePrice: 20.0,
    imageGradient: "from-rose-900 to-red-950",
    tags: [
      "hermit crab",
      "scarlet hermit",
      "red legged hermit",
      "Paguristes cadenati",
      "saltwater",
      "reef safe",
      "cleanup crew",
      "CUC",
      "invertebrate",
      "cyanobacteria",
      "20 pack",
      "bulk",
      "premium",
    ],
  },
];
