// Saltwater Products — macroalgae, corals, marine plants, inverts
// Pricing matched to Top Shelf Aquatics (topshelfaquatics.com/collections/macroalgae)
import type { Product } from "./mockData";

export const saltwaterProducts: Product[] = [
  {
    id: "sw-chaeto",
    name: "Chaetomorpha Macroalgae",
    scientificName: "Chaetomorpha linum",
    description:
      "Hardy green macroalgae prized by reefkeepers for nutrient export. Pulls nitrates and phosphates from the water column while providing shelter for copepods and amphipods. Does best when tumbled in a refugium with ample water movement. Provide adequate lighting to thrive.",
    category: "Saltwater",
    subCategory: "Macroalgae",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 29.99,
    size: "Golf ball size",
    wholesalePrice: 12.0,
    imageGradient: "from-emerald-900 to-teal-900",
    tags: [
      "macroalgae",
      "saltwater",
      "reef",
      "refugium",
      "nutrient export",
      "nitrate",
      "phosphate",
      "chaeto",
      "pod habitat",
    ],
  },
  {
    id: "sw-redogo",
    name: "Red Ogo Gracilaria Macroalgae",
    scientificName: "Gracilaria parvispora",
    description:
      "Vibrant red macroalgae that doubles as a natural nutrient exporter and a premium food for tangs and other herbivores. Absorbs nitrates and phosphates from the water column while adding striking color to refugiums and display tanks. Provide moderate flow and adequate lighting.",
    category: "Saltwater",
    subCategory: "Macroalgae",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 29.99,
    size: "Golf ball size",
    wholesalePrice: 12.0,
    imageGradient: "from-red-900 to-rose-900",
    tags: [
      "macroalgae",
      "saltwater",
      "reef",
      "refugium",
      "red ogo",
      "gracilaria",
      "tang food",
      "nutrient export",
      "herbivore",
    ],
  },
  {
    id: "sw-pompom",
    name: "Pom Pom Gracilaria Macroalgae",
    scientificName: "Gracilaria hayi",
    description:
      "Ravenous consumer of nitrates, phosphates, and dissolved organic wastes. Its tightly branched, pom-pom structure resists biofouling and creates bioactive substrate for copepods, amphipods, and beneficial microbes. Tangs and rabbitfish will readily consume this nutritious macroalgae, making it an excellent dual-purpose choice for display tanks and refugiums alike.",
    category: "Saltwater",
    subCategory: "Macroalgae",
    waterType: "Saltwater",
    availability: "AVAILABLE",
    price: 19.99,
    size: "Small / Medium",
    wholesalePrice: 7.5,
    imageGradient: "from-rose-900 to-pink-900",
    tags: [
      "macroalgae",
      "saltwater",
      "reef",
      "refugium",
      "pom pom",
      "gracilaria",
      "tang food",
      "rabbitfish",
      "nutrient export",
      "pod habitat",
    ],
  },
];
